### ISSUE TITLE
Automatically select the previously opened file

### ISSUE THREAD

**Issue by fullofcaffeine** [robinmalburn/sublime-tabfilter#5]
Hi there,

This plugin is really useful, thanks for it!

Right now, I really rely on the default behavior from the file picker of automatically selecting the previously opened file so that I can quickly switch between it and the file I'm currently editing.

I.e:

1) I open file `a`
2) I switch to file `b` using the `tabfilter` plugin
3) I open `tabfilter` again while the file `a` has focus
4) I should be able to press `<enter>` to go back to file `a`. If I repeat the process, I'll end up in file `b` a nd vice-versa.

Is it something that can be setup in `tabfilter`?

Thanks!

**Comment by robinmalburn** [comment]
Hi there,

Glad you're finding the plugin useful - always great to hear :)

That's an interesting feature idea - it's not something I'd considered for the plugin, but I can see the value.  There's nothing directly in the Plugin API to support jumping between the current and previous view, unfortunately, so it would require rolling something myself within the plugin, which gets a bit iffy.

This behaviour is sort of available already within Sublime by using ctrl+tab - however, it's essential to release the ctrl key between presses, otherwise it will cycle windows sequentially left to right instead of jumping between the last used views.  The whole needing to release control between presses is a weird little implementation detail, but otherwise I think it does what you need.

If it were to be rolled into the plugin, there are a couple of potential problems that would need resolving:

- What if the user closes the view they were previously in?  An Event Listener could be set up to check for views being closed in order to clear the remembered last view, so that might solve that problem.  In the instance that the previous tab/view is closed, I think the sanest thing to do is revert to the existing behaviour, rather than trying to re-open the old file (which otherwise introduces even more considerations).
- What about a user switching tab manually, i.e. outside of the plugin?  This could again possibly be handled via an Event Listener - the plugin could listen for view activation / deactivation and update the current / previous tab setting internally based on that.
- Representing the behaviour in the UI.  There's no way of pre-selecting an item in the quick list for the user, so the behaviour would either have to be triggered when no selection is made, or be bound as a separate command.  I think I'd be in favour of the latter so as to not behave inconsistently with other quick select boxes used within Sublime.

**Comment by robinmalburn** [comment]
I think since this hasn't seen any more discussion in a year, and the basic premise is already supported in SublimeText natively, I'm going to close the issue until it sees future requests or activity.
