### ISSUE TITLE
Pane numbers

### ISSUE THREAD

**Issue by certainlyakey** [robinmalburn/sublime-tabfilter#7]
Thanks for the great plugin! 
It would be great to have pane number available as a caption (for the first tab in each pane) or a delimiter in the list. I use many panes, and detecting where each pane starts/ends in the list is a bit difficult.

**Comment by robinmalburn** [comment]
Thanks for your comment, glad you've found the plugin useful.

Unfortunately, I don't really use Sublime much these days (switched back to vim when Sublime went through a looooong drought of not being updated), so this plugin hasn't seen much in the way of updates.  I did take a quick look at the API docs to see if what you were requesting was feasible and unfortunately, the API doesn't yield much information with regards panes; it looks like from the information I get back from the Sublime View object, the best I'd easily be able to get that would probably be usable information would be to grab the View object's unique ID and make that an optional caption to show... I'm just not sure how meaningful it would actually be in practice, unfortunately, and don't currently have a Sublime set up to test with.

If the ID approach sounds like it would reasonably cover your use case, though, let me know and I'll jury rig a set up and prototype a build to see how it looks.

**Comment by certainlyakey** [comment]
OK, no worries then. I can also try to look into this myself and then to open a PR if it works. Thanks for the hint though!

**Comment by asumaran** [comment]
Thanks for awesome plugin! I also wanted to suggest something similar. 

In my case I want to open/filter by pane. I wish I could open the dialog and the files on the list should only be the files in that current pane.

I use panes a lot and also open files a lot so panes won't show the full file names due to limited space available. So this plugin is perfect to find a desired file right away but I don't want to go to another pane because I know which pane each file is I just don't know where exactly.

**Comment by robinmalburn** [comment]
@certainlyakey I'm not sure if this feature is something you'd still be interested in, but whilst working on another new feature someone kindly submitted a PR for, their submission gave me an idea for how I could add the Caption support you'd requested ages ago.  This is my first draft of the feature with support for enabling and configuring the caption text itself - you can see an example of the default configuration below.

![Example](https://user-images.githubusercontent.com/1475492/126714089-3dfba71d-f45b-4218-9b04-8fbe6963257f.png)

Is this something you'd still be interested in?

This version doesn't solve what @asumaran was looking for yet, but it's a step closer at least, since it's at least accounting for multi-pane layouts better now.

**Comment by robinmalburn** [comment]
Turns out, there was a relatively painless solution to the feature @asumaran requested too, so I've updated the feature to support both captions and limiting filtering to the active group in the latest update.

**Comment by robinmalburn** [comment]
This is now available in release 2.0 of the package released along side the re-write for Sublime Text 4 and Python 3.8 😄   Just released it this morning, so should be showing up on Package Control soon.
